### ISSUE TITLE
Bild-DB für Karte

### ISSUE THREAD

**Issue by juauer** [juauer/modelcars#12]
Die Einzelbilder, die zusammen eine Karte ergeben, sollen über das Dateisystem verwaltet werden. Sie müssen aber indiziert werden um sinnvoll auf sie zugreifen zu können. Außerdem wird eine Policy benötigt, wann welche neuen Bilder abgelegt werden bzw. wann welche Bilder gelöscht werden. Der Ansatz ist wie folgt:

* Der Zustandsraum wird diskretisiert. Eine Zelle sollte etwa 1/4 so groß wie ein Bild sein.
* Als optimal nehmen wir ein Bild je Zelle an, das genau im Zentrum der Zelle aufgenommen wurde.
* Jede Zelle hat einen Timestamp, wann das zugehörige Bild aufgenommen wurde und die Koordinaten wo jenes aufgenommen wurde.
* Fährt das Auto innerhalb einer Zelle wird genau dann das zugehörige Bild überschrieben, wenn entweder noch keins da war, oder wenn der Timestamp zu alt ist, oder wenn die aktuelle Position näher am Zentrum der Zelle ist als das bisher zugehörige Bild.

Bilder werden immer "korrekt" gedreht abgelegt. Wird ein Bild für eine Position angefragt, wird eine Liste von Bildern zurückgegeben die auf die Anfrage passt - die Bilder dieser Liste können dann einzeln evaluiert werden (ohne potentiell teures Stitching).

Um effiziente Anfragen zu gewährleisten soll für den Index ein [range tree](https://en.wikipedia.org/wiki/Range_tree) verwendet werden.

**Comment by juauer** [comment]
Unter der Annahme <16 Bilder zu haben können wir vorerst alle Bilder im Speicher halten und mit brute-force in einem 2D-Array suchen (ersteinmal keine Suchbäume oder Ähnliches).

**Comment by juauer** [comment]
Man sollte das hier zuerst machen und die Bilder unkorrigiert ablegen, bevor man anschließend mit #11 versucht das Ergebnis zu verbessern.

**Comment by juauer** [comment]
Ich habe mal die basis Struktur gepusht.  Jetzt kann jeder an seiner Funktion fummeln.

**Comment by juauer** [comment]
Kleine Korrektur zum OP: die Kartenstücke können nicht de-rotiert abgelegt werden - das macht entweder die Bilddimensionen kaputt, oder es gehen Pixel verloren. Man muss also beim Abrufen der Kartenstücke als erstes die Rotation aus den relativen Koordinaten rausrechnen. Ich habe mal eine Helper-Funktion gepusht, mit der man Vektoren rotieren kann.

**Comment by juauer** [comment]
Wie sieht es mit dem extrahieren aus? Einfügen ist prototypisch fertig. #11 ist jetzt wieder brandaktuell - und das will ich eigentlich nicht auch noch anfassen ...

**Comment by Taehal** [comment]
Ich bin dran, kann nur leider im Moment nicht wirklich testen, da bei mir
die cp2 nicht fehlerfrei compiliert

Am 29.06.2017 10:01 vorm. schrieb "juauer" <notifications@github.com>:

**Comment by juauer** [comment]
Das einzige was derzeit nicht kompiliert, ist get_map_pieces - was ja hier ersetzt werden soll ;)
