### ISSUE TITLE
Flott 'ne neue Karte basteln

### ISSUE THREAD

**Issue by juauer** [juauer/modelcars#14]
Habe dafür ein paar Bilder gepusht. Reichen die?

**Comment by Taehal** [comment]
Kann man damit schon was anfangen oder fehlen die Randbereiche?
Dann müsste ich noch mal schauen, dass die beim drehen nicht abgeschnitten werden.

**Comment by juauer** [comment]
Sieht super aus. Rand ist eh kacke (bei der automatischen Lösung werden wir sogar absichtlich versuchen, Rand abzuschneiden. Besser nix (="das gucken wir nicht an") als Rand).
