### ISSUE TITLE
Auf feste Startposition umstellen

### ISSUE THREAD

**Issue by juauer** [juauer/modelcars#17]
Das Auto soll bei (0,0,0) starten. Dort ist auch der Ursprung des Kartenkoordinatensystems. Wir müssen:

*  Die Partikel in Frame 1 nicht gleichverteilt streuen, sondern um (0,0,0)
*  Die defaults reviewen (zB particles_keep:=1)
*  Solange wir noch die grosse Karte haben, herausfinden wo genau (in der Realität) (0,0,0) überhaupt ist
*  ... was noch?

**Comment by juauer** [comment]
Ich hätte gerne einen Switch, so dass man auf die allgemeine Lösung zurückkommen kann.

**Comment by mauriceAlthoff** [comment]
ist jetzt implementiert

**Comment by juauer** [comment]
Drei Details sind buggy:
* Wenn man doch im laufenden Betrieb resampled, werden neue Partikel stets bei der Startposition erzeugt. Man muss das initiale Verteilen auf eine init()-Methode auslagern (wollte ich sowieso). Solange man das nicht hat, ist particles_keep:=k für k!=1 ein Bug.
* Es wird nur entlang der positiven Achsen verteilt. Also zB für x: zwischen x_start und x_start+rnd. Es sollte aber _um_ den Startwert verteilt werden, also zwischen x_start-(rnd/2) und x_start+(rnd/2).
* In mindestens einem Launchfile fehlen bei der Arg-Übergabe Spaces.

**Comment by mauriceAlthoff** [comment]
in welchem launch file? Ich hab schon 5 angepasst.

**Comment by juauer** [comment]
* uniform_real_distribution [erwartet tatsächlich](http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution) a,b um in [a, b) zu verteilen. Das stimmt also immer noch nicht.
* In allen drei localization_publisher*.launch fehlt ein Space in der langen Zeile bei der Argument-Übergabe. Vielleicht ist das ja auch egal? Habe es nicht laufen lassen.
* Ach, was ich gerade noch sehe: der argc<x check braucht noch ein größeres x.

**Comment by juauer** [comment]
Der Call auf uniform_real_distribution war immer noch buggy. Bei Interesse vielleicht doch mal den Link oben anklicken. Ich habe das jetzt gefixt.
