### ISSUE TITLE
Branch für große Karte

### ISSUE THREAD

**Issue by juauer** [juauer/modelcars#19]
* ggf. bbox in map.*pp passend fest setzen
* Ausprobieren, wo (0,0,0) in der Welt liegt und an geeignetem Ort notieren
* Laufen lassen und gucken, was passiert

**Comment by mauriceAlthoff** [comment]
Bei den Aufnahmen hatten wir glück und das auto fängt in der nähe von (0,0) an. Aber wie setze ich die anzahl der zufällig gestreuten Partikel auf null? Wenn ich particles_keep auf 1 setzte gibt es einen Fehler.

**Comment by mauriceAlthoff** [comment]
Es gibt jetzt einen neuen Branch MVP1 dort wird mit den großen Karte weiter entwickelt.

**Comment by juauer** [comment]
Das Auto fängt etwa bei (1, 0.5) an (oder war es (0.5, 1) ?). Ich hatte das letzte Woche kurz hart gecodet, als ich das Bild für die Chefs gemalt habe.

particles_keep:=1 sollte derzeit default sein und ist bereits getestet. Wenn es da einen Fehler gibt, ist das ein Bug der mit den commits der letzten zwei Tage gekommen sein muss. Ich gucke mir das mal an.

**Comment by juauer** [comment]
#17 hatte immer noch einen Bug, der dieses Problem ausgelöst hat. Ist gefixt.

**Comment by juauer** [comment]
Wo ist denn jetzt (0,0,0) in der Welt? Vielleicht kann man ein Foto machen. Es genügen bestimmt +-20cm / +-20°.

Wie sieht es aus (visuelle Kontrolle)? Kann der Filter bei zufälligem Rumfahren zuverlässig tracken?

**Comment by mauriceAlthoff** [comment]
Es funktioniert gut mit 0,0. Das starten dauert bei mir zu lange um den unterschied zu sehen, weil der filter zu schnell konvergiert in beiden fällen.

**Comment by juauer** [comment]
Missverständnis: wir brauchen nicht (nur) die Koordinaten der Aufnahme (egal ob (0,0), (1,1) or whatever), sondern die Information, wo (0,0) in der "echten" Welt ist.

* Die Karte liegt fest mit ihrem Mittelpunkt auf (0,0)
* Die Startposition für das Auto soll fest sein (z.B. (0,0) )
* Wo stellen wir das Auto jetzt beim Losfahren auf?

p.s.: sobald ein bag läuft kann man "Space" drücken (stdin) um auf "Pause" zu schalten. Danach kann man mit "s" durch den bag steppen oder mit "Space" wieder auf "Play" schalten. Das ist praktisch.

**Comment by mauriceAlthoff** [comment]
Hab ein neues Ticket #23 dafür  aufgemacht, Branch ist da, schließe damit dieses Issue
