### ISSUE TITLE
Switch für linearen/log Fehler

### ISSUE THREAD

**Issue by juauer** [juauer/modelcars#2]
Die aktuell verwendeten Fehlerfunktionen sind eher "optimistisch", d.h. der Fehler ist quasi nie größer 0.7 aber sehr gerne kleiner 0.5. Aktuell wird wird der Fehler e deshalb künstlich zu max(1, 2*e) verschlechtert, um weniger optimistisch zu sein.

Besser ist es bestimmt logarithmisch zu skalieren, so dass die Information die beim cappen (Aufruf von max() ) verloren geht erhalten bleibt. Man verliert so zwar an anderer Stelle Information, aber erst weit hinter'm Komma (und somit auch hinter der Genauigkeit des Algos).

Die künstliche Verschlechterung des Fehlers im ImageEvaluator soll für die einzelnen Fehlerfunktionen entfernt werden und statt dessen eine logarithmische Skalierung des am Ende zurückgegebenen Fehlers vorgenommen werden.

Bitte einen Parameter rausgeben um den pessimistischen Fehler ein- und auszuschalten.

**Comment by mauriceAlthoff** [comment]
Das wurde ja in der Besprechung mit Hamid gemacht kannst du das bitte pushen?

**Comment by juauer** [comment]
Nochmal für alle die Kurzform für's Verständnis:

Man betrachte diesen [Plot](https://www.graphsketch.com/?eqn1_color=1&eqn1_eqn=exp(-16*x*x)&eqn2_color=2&eqn2_eqn=(x%3C0.5)*(1-2*x)&eqn3_color=3&eqn3_eqn=&eqn4_color=4&eqn4_eqn=&eqn5_color=5&eqn5_eqn=&eqn6_color=6&eqn6_eqn=&x_min=-0.5&x_max=1.5&y_min=-0.5&y_max=1.5&x_tick=1&y_tick=1&x_label_freq=1&y_label_freq=1&do_grid=0&do_grid=1&bold_labeled_lines=0&bold_labeled_lines=1&line_width=4&image_w=850&image_h=525). Wenn x unser Fehler und y unser Belief ist, zeigt die rote Funktion unsere bisherige Berechnung und die blaue Funktion das, was wir - wie mit Hamid besprochen - ab jetzt machen.
