### ISSUE TITLE
Testaufnahmen

### ISSUE THREAD

**Issue by mauriceAlthoff** [juauer/modelcars#21]
Partikel Filter mit dem Modellauto laufen lassen und Aufzeichnung machen.

**Comment by juauer** [comment]
Bitte nicht vergessen, bei zumindest einer Kreis-Fahrt auch den Radius des Kreises zu messen.

**Comment by mauriceAlthoff** [comment]
Jemand hat die catkin und die ros Environment auf dem auto gelöscht, bin wohl heute damit beschäftigt das Auto wieder zum laufen zu kriegen.

**Comment by juauer** [comment]
Hat's geklappt?

**Comment by mauriceAlthoff** [comment]
Nein, der localization_publisher wird nicht aufgerufen. Ich hab gestern die Kamera auf einem  neuem Auto montiert und die Umgebung zum laufen gebracht.  
Heute dann den localizer vom Notebook laufen lassen hat aber nicht funktioniert daher kompiliere ich gerade alles auf dem Auto und versuche es da zum laufen zu kriegen.

**Comment by mauriceAlthoff** [comment]
It's [alive!!!](http://gph.is/1NZFbkg) Houston, we have contact. Nachdem jmd. diese Woche wieder das Auto unbrauchbar gemacht hat. Hab ich es doch echt heute geschafft es auf dem Auto zum laufen zu kriegen wir kriegen eine position alle 4.5 hz.  Also morgen sollten wir aufnahmen machen können. Ich versuch dann noch den master Branch zum laufen zu kriegen.

**Comment by mauriceAlthoff** [comment]
Hab die Änderungen um die dynamische karte auf dem auto zu kompilieren in  den neuen branch "master-indigo" gepackt und ein paar launch Files in MVP1, die das starten des GPS vereinfacht. Ich sollte das starten des GPS in der README oder irgendwo anders noch beschreiben. Es sollte morgen den Testaufnahmen nichts mehr im weg stehen.
