### ISSUE TITLE
GroundTruth zum Laufen bringen

### ISSUE THREAD

**Issue by juauer** [juauer/modelcars#22]
Rausfinden, wie die Deckenkamera funktioniert und sie benutzen, um Vergleichswerte zu bekommen.

**Comment by mauriceAlthoff** [comment]
Die Kameras sind mit usb anzusteuern und man kann Sie mit usb_cam packet aus dem [wiki](https://github.com/AutoModelCar/model_car) als rosbag aufnehmen. Hier die Parameter um autofokus auszustellen
-Kamera 1:
v4l2-ctl -d 0 --set-ctrl focus_auto=0
v4l2-ctl -d 0 --set-ctrl focus_absolute=0
v4l2-ctl -d 0 --set-ctrl contrast=0
v4l2-ctl -d 0 --set-ctrl brightness=0

-Kamera2:
v4l2-ctl -d 1 --set-ctrl focus_auto=0
v4l2-ctl -d 1 --set-ctrl focus_absolute=0
v4l2-ctl -d 1 --set-ctrl contrast=0
v4l2-ctl -d 1 --set-ctrl brightness=0

**Comment by mauriceAlthoff** [comment]
Im MVP1 Branch ist jetzt ein launch file um beide kameras zu publishen
