### ISSUE TITLE
Master wieder zum Master machen

### ISSUE THREAD

**Issue by juauer** [juauer/modelcars#24]
Ich habe beschlossen, dass die ausführlichen Includes aus f861ba1bea6f91ce9d7266690d02326a008f47a2 der einfachste Weg sind, das Kompilier-Problem zu lösen und habe den Commit in den Master gecherry-picked.

Ich habe den Commit danch (f861ba1bea6f91ce9d7266690d02326a008f47a2) auch geholt, aber etwas verändert:
* das Profil gab es schon (genau so) man soll aber crosscompile/install benutzen, damit der Pfad zum Toolchain File nicht absolut angegeben werden muss. Bei jedem anderen außer dem Autor würde es sonst nicht kompilieren (falscher Pfad) ;) Siehe auch 2b2bcd2c8c29742a5c414a4d1b522f3afb01e8ea !
* die anderen Files habe ich nach / geschoben. Fragen / Issues dazu:
    * was ist mit diesem .txt file? Ist das nicht eigentlich ein Launchfile?
    * der environment 'Hack' muss weg, sonst kann das ja außer uns nie jemand starten / verstehen / warten
    * replace.sh muss bestimmt angepasst werden, nach den von mir vorgenommenen Änderungen. Erbitte review.

Den Branch können wir löschen !?

**Comment by mauriceAlthoff** [comment]
Das Odroid Profil ist dann überflüssig (hatte immer nur die x86 Umgebungen vorgeschlagen bekommen bei auto completion??? hab das arm zeug bestimmt nur übersehen)

Zu den Dateien:
-  Der Environment Hack ist mir auch bewusst das ich das noch ändern muss aber ich wollte ihn erstmal dokumentieren :-D. damit das nicht nur ich weiß.
- Das txt ist nur eine Notiz und ist mittlerweile ein launchfile (... Das nach langer suche scheinbar noch nicht von mir eingecheckt ist)
- replace.sh ist das script aus [catkin_ws_user](https://github.com/AutoModelCar/catkin_ws_user/blob/master/replace.sh) alles mit dem odroid profile zu kompilieren. Das muss nicht geändert werden und ist da um das testen von code auf dem odroid zu beschleunigen. [siehe](https://github.com/AutoModelCar/AutoModelCarWiki/wiki/Cross-compile) 

Ich lösche den branch, nachdem ich die launchfiles zum testen von control hochgeladen habe.

**Comment by juauer** [comment]
Warning: Ich habe gestern mit Zahra gesprochen, die wohl alle Odroids mit Kinetic geflasht hat ...

Dann müssen wir wohl eh noch mal umstellen ("yay"...)

Sind aber vielleicht auch ein paar Probleme los (yay!).

Nächstes Mal wenn ich im Lab bin, klemm' ich mich auch an's Auto. Vielleicht schaffe ich es sogar morgen (Do).

**Comment by juauer** [comment]
Ach, und bzgl.:

> hab das arm zeug bestimmt nur übersehen

wenn man vergisst crosscompile/install.sh auszuführen, ist das arm profil nicht vorhanden - vielleicht lag da der Hase im Pfeffer ...

**Comment by juauer** [comment]
Ich habe mir das heute mal angeschaut: auf den Autos ist jetzt tatsächlich xenial / kinetic / CV-3.2. Gibt man die richtige CV Version an, kompiliert unser Code auf den Autos.

Crosskompilieren geht nun erst einmal nicht mehr, bis "jemand" die Toolchain, etc. anpasst.

Es ist ratsam, auf allen PCs ebenfalls auf xenial / kinetic / CV-3.2 umzusteigen.

Ich nehme jetzt alle entsprechenden Änderungen vor.
