### ISSUE TITLE
Dokumentieren wie das Positionssystem zu starten ist in der odroid Umgebung 

### ISSUE THREAD

**Issue by mauriceAlthoff** [juauer/modelcars#26]
- Wie Cross Compiliere ich cps2
- Wie kopiere ich die binaries
- Wie starte ich das Positionsystem auf dem auto

**Comment by juauer** [comment]
> Wie Cross Compiliere ich cps2

Gar nicht - siehe #27

> Wie kopiere ich die binaries

Gar nicht - Du hast keine (again: #27). Man muss aktuell den catkin_ws rüberkopieren und dort kompilieren.

> Wie starte ich das Positionsystem auf dem auto
 
Ich habe in c5e6fb2ede8bc3d9d7ee71bfdc5987ced5c729cd das README mit Instruktionen (und TODOs) gefüllt.
