### ISSUE TITLE
Binning

### ISSUE THREAD

**Issue by juauer** [juauer/modelcars#4]
Man kann ein Cluster von plausiblen Partikeln haben, aber genau der eine mit der korrekten Rotation ist nicht dabei. Wie bedauerlich, dass wir aktuell nur die Information aus dem besten Partikel verwenden und die zusätzliche Information die im Cluster steckt wegwerfen.

Beim Binning wird der Zustandsraum diskretisiert (in eine Anzahl Bins fester Größe). Während man die Beliefs für die Partikel ausrechnet werden die Partikel (in der selben Schleife) dem jeweils passenden Bin zugeordnet. Das Output des PFs ist jetzt nicht mehr ein bester Partikel, sondern der Mittelwert der Partikel des Bins mit dem höchsten Belief (der Einfluss einzelner Partikel wird hier natürlich mit dem jeweiligen Belief skaliert).

Bitte on/off Parameter hinzufügen.

**Comment by mauriceAlthoff** [comment]
Es fehlt noch der Parameter zum einschalten

**Comment by juauer** [comment]
bin_size:=0  bedeutet: aus.

Ist im launchfile dokumentiert.

Ein Parameter weniger ^^
