### ISSUE TITLE
Policy für Partikel am Kartenrand

### ISSUE THREAD

**Issue by juauer** [juauer/modelcars#5]
Aktuell werden die (x,y) Koordinaten eines Partikels gecappt, wenn er vom Odometrie-Update über den Kartenrand geschoben wird. Alternativ könnte man auch
*  den Partikel wegwerfen
*  den Belief des Partikels verringern

Cappen und wegwerfen macht keinen Sinn mehr, sobald wir über dynamische Karten nachdenken - eine Position für die schlicht keine Kartendaten existieren ist per se nicht unplausibel.

Es soll deshalb die aktuelle Policy ersetzt werden: Partikel die beim Motion-Update über den Rand geschoben werden sollen mit den außerhalb der Karte liegenden Koordinaten behalten werden, dafür soll in der Evaluation jeder Partikel außerhalb ein verringertes Gewicht bekommen.

Der Faktor um den das Gewicht verkleinert wird soll linear sein und als Parameter rausgegeben werden.

**Comment by juauer** [comment]
Jetzt ist es ein Bug.
*  Das Ändern des Gewichts muss(!) wie bereits erwähnt im Evaluations-Schritt und nicht im Motion-Update erfolgen. Oder besser an beiden Stellen. In der Reihenfolge wie die Methoden im Moment aufgerufen werden (MU->Eval->getBest) würde das geänderte Gewicht direkt wieder überschrieben werden.
*  Der Skalierungsfaktor soll ein Parameter sein.
*  '0' ist eine valide Koordinate. Also muss man entweder entweder <0 oder <=-1 filtern, aber nicht <=0.

**Comment by mauriceAlthoff** [comment]
Bug sollte gefixed sein Schliesse wieder das Ticket

**Comment by juauer** [comment]
Alte Bugs:
* Das ganze capping (die mins und maxs) im Motion Update muss natürlich weg (das war ja der Sinn der Sache). Das hatte ich beim reopening übersehen.

Neue Bugs:
* in den cps2 launchfiles wird punishEdgeParticlesRate nicht an den node übergeben
* im test launchfile fehlt der Parameter ganz
* im printf vom publisher fehlt das "%.f" für die punishEdgeParticlesRate

Holzauge sei wachsam oO
